version: "3.9"

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=lab3
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret123
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./dockerData/db:/var/lib/postgresql/data/
